"""
git_ops/agents_md.py — Generate agents.md content for AI agent discoverability.
"""

import re
import uuid
from datetime import datetime


def _slug(name: str) -> str:
    """Lowercase-hyphenated slug for folder/file names."""
    s = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "", name).strip(". ")
    s = s.lower().replace(" ", "-")
    return re.sub(r"-+", "-", s).strip("-")


def _generate_run_id() -> str:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique = uuid.uuid4().hex[:6]
    return f"{timestamp}_{unique}"


def generate_agents_md(
    results_summary: list,
    tfm: str = "net9.0",
    nuget_version: str = "26.2.0",
    run_id: str = None,
) -> str:
    """Generate root-level agents.md content."""
    if not run_id:
        run_id = _generate_run_id()

    total = len(results_summary)
    passed = sum(1 for r in results_summary if r.get("status") == "PASSED")
    pass_rate = (passed / total * 100) if total > 0 else 0

    categories = {}
    for result in results_summary:
        cat = result.get("category", "uncategorized")
        if cat not in categories:
            categories[cat] = {"total": 0, "passed": 0}
        categories[cat]["total"] += 1
        if result.get("status") == "PASSED":
            categories[cat]["passed"] += 1

    category_details = ""
    for cat, stats in sorted(categories.items()):
        cat_pass_rate = (stats["passed"] / stats["total"] * 100) if stats["total"] > 0 else 0
        cat_slug = _slug(cat)
        category_details += f"### {cat}\n"
        category_details += f"- Examples: {stats['total']}\n"
        category_details += f"- Pass Rate: {stats['passed']}/{stats['total']} ({cat_pass_rate:.0f}%)\n"
        category_details += f"- Guide: [agents.md](./{cat_slug}/agents.md)\n\n"

    current_date = datetime.now().strftime("%Y-%m-%d")

    content = f"""# Aspose.PDF for .NET Examples

AI-friendly repository containing validated C# examples for Aspose.PDF for .NET API.

## Repository Overview

This repository contains **{total}** working code examples demonstrating Aspose.PDF for .NET capabilities.

**Statistics** (as of {current_date}):
- Total Examples: {total}
- Categories: {len(categories)}
- Pass Rate: {pass_rate:.1f}%

## Category Details

{category_details}## How to Use These Examples

### Prerequisites
- .NET SDK ({tfm.replace('net', '').replace('.0', '.0')} or higher)
- Aspose.PDF for .NET ({nuget_version} or higher)
- NuGet package restore enabled

### Running an Example
1. Navigate to any category folder
2. Each .cs file is a standalone Console Application
3. Ensure `input.pdf` exists in the same directory (where required)
4. Compile and run:
   ```bash
   dotnet run <example-file.cs>
   ```

## Code Conventions
- **No `var` keyword**: All types explicitly declared
- **One-based indexing**: Aspose.PDF uses 1-based page indexing
- **Deterministic cleanup**: All IDisposable objects wrapped in `using` blocks

<!-- AUTOGENERATED:START -->
Updated: {current_date} | Run: `{run_id}`
<!-- AUTOGENERATED:END -->

---

*This repository is maintained by automated code generation. Last updated: {current_date} | Total examples: {total} | Pass rate: {pass_rate:.1f}%*
"""
    return content


def generate_category_agents_md(
    category: str,
    files: list,
    stats: dict,
    run_id: str = None,
) -> str:
    """Generate per-category agents.md guide."""
    if not run_id:
        run_id = _generate_run_id()

    file_list = ""
    if files:
        for filename in sorted(files):
            display_name = filename.replace(".cs", "")
            file_list += f"- [{display_name}](./{filename})\n"
    else:
        file_list = "*No examples in this category yet.*"

    pass_rate = stats.get("pass_rate", 0)
    total = stats.get("total", 0)
    passed = stats.get("passed", 0)
    current_date = datetime.now().strftime("%Y-%m-%d")

    return f"""# AGENTS - {category}

## Scope
- This folder contains examples for **{category}**.
- Files are standalone `.cs` examples stored directly in this folder.

## Files in this folder
{file_list}

## Category Statistics
- Total examples: {total}
- Passed: {passed}
- Failed: {total - passed}
- Pass rate: {pass_rate:.1f}%

## Category Tips
- See parent [agents.md](../agents.md) for repository-level patterns
- Review code examples in this folder for {category} patterns

<!-- AUTOGENERATED:START -->
Updated: {current_date} | Run: `{run_id}`
<!-- AUTOGENERATED:END -->
"""


def apply_autogenerated_markers(existing_content: str, new_content: str) -> str:
    """Update auto-generated section while preserving manual edits."""
    start_marker = "<!-- AUTOGENERATED:START -->"
    end_marker = "<!-- AUTOGENERATED:END -->"

    if not existing_content:
        return new_content

    if start_marker in existing_content and end_marker in existing_content:
        start_idx = existing_content.find(start_marker)
        end_idx = existing_content.find(end_marker) + len(end_marker)

        new_start_idx = new_content.find(start_marker)
        new_end_idx = new_content.find(end_marker) + len(end_marker)

        if new_start_idx >= 0 and new_end_idx > new_start_idx:
            new_section = new_content[new_start_idx:new_end_idx]
            return existing_content[:start_idx] + new_section + existing_content[end_idx:]

    return new_content
