"""
git_ops/agents_md.py — Generate agents.md content for AI agent discoverability.
"""

import re
import uuid
from datetime import datetime

from git_ops.agents_content import (
    build_boundaries,
    build_code_intelligence_sections,
    build_command_reference,
    build_frontmatter,
    build_persona,
    build_testing_guide,
    load_anti_patterns,
    load_category_tips,
    load_domain_knowledge,
)


def _slug(name: str) -> str:
    """Lowercase-hyphenated slug for folder/file names."""
    s = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "", name).strip(". ")
    s = s.lower().replace(" ", "-")
    return re.sub(r"-+", "-", s).strip("-")


def _generate_run_id() -> str:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    unique = uuid.uuid4().hex[:6]
    return f"{timestamp}_{unique}"


def generate_agents_md(
    results_summary: list,
    tfm: str = "net10.0",
    nuget_version: str = "26.2.0",
    run_id: str = None,
    error_catalog_path: str = "",
    error_fixes_path: str = "",
    kb_path: str = "",
) -> str:
    """Generate root-level agents.md content.

    When resource paths are provided, injects prescriptive sections:
    - Frontmatter, persona, boundaries (GitHub best practices)
    - Common mistakes (anti-patterns) from error_catalog + error_fixes
    - Domain knowledge from kb.json
    - Command reference and testing guide for dotnet build/run
    """
    if not run_id:
        run_id = _generate_run_id()

    total = len(results_summary)

    categories = {}
    for result in results_summary:
        cat = result.get("category", "uncategorized")
        if cat not in categories:
            categories[cat] = {"total": 0}
        categories[cat]["total"] += 1

    category_details = ""
    for cat, stats in sorted(categories.items()):
        cat_slug = _slug(cat)
        category_details += f"### {cat}\n"
        category_details += f"- Examples: {stats['total']}\n"
        category_details += f"- Guide: [agents.md](./{cat_slug}/agents.md)\n\n"

    current_date = datetime.now().strftime("%Y-%m-%d")

    # Build sections from resource files
    frontmatter = build_frontmatter(tfm, nuget_version)
    persona_section = build_persona()
    boundaries_section = build_boundaries()
    anti_patterns_section = load_anti_patterns(error_catalog_path, error_fixes_path) if error_catalog_path else ""
    domain_section = load_domain_knowledge(kb_path) if kb_path else ""
    command_section = build_command_reference(tfm, nuget_version)
    testing_section = build_testing_guide(tfm)

    content = f"""{frontmatter}# Aspose.PDF for .NET Examples

AI-friendly repository containing validated C# examples for Aspose.PDF for .NET API.

{persona_section}## Repository Overview

This repository contains **{total}** verified C# examples demonstrating Aspose.PDF for .NET capabilities.

- Total Examples: {total}
- Categories: {len(categories)}

## Category Details

{category_details}{boundaries_section}{anti_patterns_section}{domain_section}{command_section}{testing_section}## How to Use These Examples

### Prerequisites
- .NET SDK ({tfm.replace('net', '').replace('.0', '.0')} or higher)
- Aspose.PDF for .NET ({nuget_version} or higher)
- NuGet package restore enabled

### Running an Example
1. Navigate to any category folder
2. Each .cs file is a standalone Console Application
3. Ensure `input.pdf` exists in the same directory (where required)
4. Compile and run:
   ```bash
   dotnet run <example-file.cs>
   ```

<!-- AUTOGENERATED:START -->
Updated: {current_date} | Run: `{run_id}`
<!-- AUTOGENERATED:END -->

---

*This repository is maintained by automated code generation. Last updated: {current_date} | Total examples: {total}*
"""
    return content


def generate_category_agents_md(
    category: str,
    files: list,
    stats: dict,
    run_id: str = None,
    kb_path: str = "",
    repo_path: str = "",
    tfm: str = "net10.0",
    nuget_version: str = "26.2.0",
) -> str:
    """Generate per-category agents.md guide.

    When *repo_path* is provided, enriches output with code intelligence
    (required namespaces, common code pattern, file summary table).
    When *kb_path* is provided, injects category-specific tips.
    """
    if not run_id:
        run_id = _generate_run_id()

    total = stats.get("total", 0) or len(files)
    current_date = datetime.now().strftime("%Y-%m-%d")

    # Frontmatter + persona
    frontmatter = build_frontmatter(tfm, nuget_version, is_category=True, category_name=category)
    persona_section = build_persona(is_category=True, category_name=category)

    # Code intelligence from actual .cs files
    code_intel = build_code_intelligence_sections(repo_path, category, files) if repo_path else ""

    if code_intel:
        file_section = code_intel
    else:
        # Fallback: simple file list
        if files:
            file_list = ""
            for filename in sorted(files):
                display_name = filename.replace(".cs", "")
                file_list += f"- [{display_name}](./{filename})\n"
        else:
            file_list = "*No examples in this category yet.*\n"
        file_section = f"## Files in this folder\n{file_list}\n"

    # Category-specific tips from kb.json
    category_tips = load_category_tips(kb_path, category) if kb_path else ""

    return f"""{frontmatter}# AGENTS - {category}

{persona_section}## Scope
- This folder contains **{total}** verified examples for **{category}**.
- Files are standalone `.cs` examples stored directly in this folder.

{file_section}{category_tips}## General Tips
- See parent [agents.md](../agents.md) for:
  - **Boundaries** — Always / Ask First / Never rules for all examples
  - **Common Mistakes** — verified anti-patterns that cause build failures
  - **Domain Knowledge** — cross-cutting API-specific gotchas
  - **Testing Guide** — build and run verification steps
- Review code examples in this folder for {category} patterns

<!-- AUTOGENERATED:START -->
Updated: {current_date} | Run: `{run_id}`
<!-- AUTOGENERATED:END -->
"""


def apply_autogenerated_markers(existing_content: str, new_content: str) -> str:
    """Update auto-generated section while preserving manual edits."""
    start_marker = "<!-- AUTOGENERATED:START -->"
    end_marker = "<!-- AUTOGENERATED:END -->"

    if not existing_content:
        return new_content

    if start_marker in existing_content and end_marker in existing_content:
        start_idx = existing_content.find(start_marker)
        end_idx = existing_content.find(end_marker) + len(end_marker)

        new_start_idx = new_content.find(start_marker)
        new_end_idx = new_content.find(end_marker) + len(end_marker)

        if new_start_idx >= 0 and new_end_idx > new_start_idx:
            new_section = new_content[new_start_idx:new_end_idx]
            return existing_content[:start_idx] + new_section + existing_content[end_idx:]

    return new_content
