"""
git_ops/pr.py — PRManager: create PR, update agents.md, retry PR.
"""

import subprocess
import uuid
from typing import Callable, List, Optional

from config import AppConfig
from git_ops.agents_md import (
    apply_autogenerated_markers,
    generate_agents_md,
    generate_category_agents_md,
)
from git_ops.committer import slugify, normalize_category
from git_ops.github_api import GitHubAPI
from git_ops.repo import RepoManager, _git_lock

Notify = Callable[[str, str], None]


def _noop(stage: str, msg: str):
    pass


class PRManager:
    """Handles PR creation, agents.md updates, and PR retry."""

    def __init__(self, config: AppConfig, repo: RepoManager, notify: Notify = None, llm_client=None):
        self.config = config
        self.repo = repo
        self._notify = notify or _noop
        self._llm = llm_client
        self._gh = GitHubAPI(config.git.repo_token) if config.git.repo_token else None

    def create_pull_request(self, results_summary: list) -> Optional[str]:
        """Create a GitHub PR for the current PR branch."""
        if not self.repo.pr_branch:
            return None

        owner, repo_name = GitHubAPI.extract_repo_info(self.config.git.repo_url)
        if not owner or not repo_name or not self._gh:
            self._notify("pr_error", "PR: Could not determine repository or no token")
            return None

        base_branch = self.config.git.repo_branch or "main"

        # Generate PR details via LLM (with fallback)
        self._notify("pr_create_start", "PR: Generating details and creating pull request...")
        pr_details = None
        if self._llm:
            pr_details = self._llm.generate_pr_details(results_summary)

        if pr_details:
            title = pr_details["title"]
            body = pr_details["body"]
        else:
            passed = sum(1 for r in results_summary if r.get("status") == "PASSED")
            categories = sorted(set(r.get("category", "") for r in results_summary if r.get("category")))
            title = f"Add {passed} code example(s)"
            body = (
                f"## Auto-generated Code Examples\n\n"
                f"**{passed} example(s)** added across "
                f"{len(categories)} {'category' if len(categories) == 1 else 'categories'}\n\n"
                f"**Categories:** {', '.join(categories) if categories else 'uncategorized'}\n\n"
                f"---\n*Generated by Examples Generator*"
            )

        # Update agents.md if enabled
        if self.config.git.update_agents_md:
            self._update_agents_md(owner, repo_name, base_branch, results_summary)

        # Create PR
        self._notify("pr_api_call", "PR: Creating pull request on GitHub...")
        pr_url = self._gh.create_pull_request(
            owner, repo_name, title, body,
            self.repo.pr_branch, base_branch,
        )
        if pr_url:
            self._notify("pr_create_success", "PR: Pull request created successfully")
        else:
            self._notify("pr_error", "PR: Creation failed")
        return pr_url

    def _update_agents_md(self, owner: str, repo_name: str, base_branch: str, results_summary: list):
        """Update root and category agents.md files via GitHub API."""
        try:
            self._notify("agents_md_start", "agents.md: Generating content...")
            from git_ops.agents_md import _generate_run_id
            run_id = _generate_run_id()

            # Root agents.md
            agents_content = generate_agents_md(
                results_summary,
                tfm=self.config.build.tfm,
                nuget_version=self.config.build.nuget_version,
                run_id=run_id,
            )

            existing_base = self._gh.get_file(owner, repo_name, "agents.md", base_branch)
            existing_branch = self._gh.get_file(owner, repo_name, "agents.md", self.repo.pr_branch)
            if existing_base:
                existing_content = GitHubAPI.decode_base64(existing_base.get("content", ""))
                agents_content = apply_autogenerated_markers(existing_content, agents_content)
            sha = existing_branch.get("sha") if existing_branch else None

            action = "Update" if sha else "Add"
            self._gh.create_or_update_file(
                owner, repo_name, "agents.md", agents_content,
                f"{action} agents.md with {len(results_summary)} examples",
                self.repo.pr_branch, sha,
            )

            # Category-level agents.md files
            categories_dict = {}
            for result in results_summary:
                cat = result.get("category", "uncategorized")
                if cat not in categories_dict:
                    categories_dict[cat] = {"total": 0, "passed": 0, "files": []}
                categories_dict[cat]["total"] += 1
                if result.get("status") == "PASSED":
                    categories_dict[cat]["passed"] += 1
                task = result.get("task", "")
                if task:
                    filename = slugify(task, max_len=120) + ".cs"
                    categories_dict[cat]["files"].append(filename)

            for category, cat_stats in sorted(categories_dict.items()):
                cat_pass_rate = (cat_stats["passed"] / cat_stats["total"] * 100) if cat_stats["total"] > 0 else 0
                cat_path = f"{category}/agents.md"
                cat_content = generate_category_agents_md(
                    category, cat_stats["files"],
                    {"total": cat_stats["total"], "passed": cat_stats["passed"], "pass_rate": cat_pass_rate},
                    run_id,
                )

                existing_cat_base = self._gh.get_file(owner, repo_name, cat_path, base_branch)
                existing_cat_branch = self._gh.get_file(owner, repo_name, cat_path, self.repo.pr_branch)
                if existing_cat_base:
                    existing_cat_content = GitHubAPI.decode_base64(existing_cat_base.get("content", ""))
                    cat_content = apply_autogenerated_markers(existing_cat_content, cat_content)
                cat_sha = existing_cat_branch.get("sha") if existing_cat_branch else None

                cat_action = "Update" if cat_sha else "Add"
                self._gh.create_or_update_file(
                    owner, repo_name, cat_path, cat_content,
                    f"{cat_action} {cat_path} ({cat_stats['total']} examples)",
                    self.repo.pr_branch, cat_sha,
                )

            self._notify("agents_md_success", "agents.md: Updated successfully")
        except Exception as e:
            self._notify("agents_md_error", f"agents.md: {str(e)[:100]} (non-fatal)")

    def retry_pr(self, old_pr_branch: str, results_summary: list) -> Optional[str]:
        """Create a new conflict-free PR from already-generated examples."""
        if not self.repo.ensure_ready():
            return None

        owner, repo_name = GitHubAPI.extract_repo_info(self.config.git.repo_url)
        if not owner or not repo_name:
            return None

        base = self.config.git.repo_branch or "main"
        new_branch = f"examples/retry-{uuid.uuid4().hex[:8]}"
        repo_path = self.config.git.repo_path

        try:
            with _git_lock:
                subprocess.run(
                    ["git", "fetch", "origin", base, old_pr_branch],
                    cwd=repo_path, check=True, capture_output=True, text=True,
                )
                subprocess.run(
                    ["git", "checkout", "-b", new_branch, f"origin/{base}"],
                    cwd=repo_path, check=True, capture_output=True, text=True,
                )

                files_ok = 0
                for result in results_summary:
                    category = result.get("category", "")
                    task = result.get("task", "")
                    if not task:
                        continue
                    cat_dir = normalize_category(category)
                    filename = slugify(task, max_len=120) + ".cs"
                    file_path = f"{cat_dir}/{filename}"
                    r = subprocess.run(
                        ["git", "checkout", f"origin/{old_pr_branch}", "--", file_path],
                        cwd=repo_path, capture_output=True, text=True,
                    )
                    if r.returncode == 0:
                        files_ok += 1

                status_out = subprocess.run(
                    ["git", "status", "--porcelain"],
                    cwd=repo_path, check=True, capture_output=True, text=True,
                ).stdout.strip()

                if status_out:
                    subprocess.run(
                        ["git", "commit", "-m", f"Add {files_ok} code example(s) (retry)"],
                        cwd=repo_path, check=True, capture_output=True, text=True,
                    )

                subprocess.run(
                    ["git", "push", "-u", "origin", new_branch],
                    cwd=repo_path, check=True, capture_output=True, text=True, timeout=60,
                )

        except subprocess.TimeoutExpired:
            self._notify("git_error", "Git: Push timed out")
            return None
        except Exception as e:
            self._notify("git_error", f"Git: Operations failed - {str(e)[:100]}")
            return None

        self.repo.pr_branch = new_branch
        return self.create_pull_request(results_summary)
